# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-27 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_auto_20171005_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Wedding', 'Wedding'), ('Debut', 'Debut'), ('Birthday', 'Birthday'), ('Thanksgiving', 'Thanksgiving')], default='Wedding', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='package_images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='max_budget',
            field=models.IntegerField(default=0),
        ),
    ]
