# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-05 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover_photo',
            field=models.ImageField(default='cover_photos/None/no-img.jpg', upload_to='cover_photos/'),
        ),
    ]
