# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-13 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0004_auto_20180112_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='fax_no',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='tel_no',
        ),
        migrations.AddField(
            model_name='profile',
            name='business_permit',
            field=models.ImageField(blank=True, null=True, upload_to='documents/business_permit/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='business_plate',
            field=models.ImageField(blank=True, null=True, upload_to='documents/business_plate/'),
        ),
    ]
